### ISSUE TITLE
Duplicated entries (entries of an earthquake with same station coordinate)

### ISSUE THREAD

**Issue by bc88bc** [personlin/TGMM#12]
Keep only one of the duplicates.
[duplicated.txt](https://github.com/personlin/TGMM/files/483896/duplicated.txt)

**Comment by personlin** [comment]
Two type of duplicated record at same coordinate,
1. multiple instruments at the same station.
2. duplicated station at the same location. (ex: TAP, TAP001)

**Comment by personlin** [comment]
The selection of records was base on _usable_period_H_.
If one location has more than 2 records, the record with **median** _usable_period_H_ will be select.
If one location has two records with **different** _STA_ID_, the record with **six code TSMIP** station will be select.
If one location has two records with **same** _STA_ID_, the record with **larger** _usable_period_H_ will be select.
