### ISSUE TITLE
Column ‘usable_period_H' is NA for 12,114 records

### ISSUE THREAD

**Issue by bc88bc** [personlin/TGMM#7]
1. Why NA exists?
2. For these records, how do I obtain the lowest usable period?

**Comment by personlin** [comment]
This column was updated.
Lowest_Usable_Freq_H1  = HP_H1_1.25
Lowest_Usable_Freq_H2  = HP_H2_1.25
Lowest_Usable_Freq_Ave = max(Lowest_Usable_Freq_H1, Lowest_Usable_Freq_H2)
usable_period_H = 1/Lowest_Usable_Freq_Ave
