### ISSUE TITLE
Use NA for -999

### ISSUE THREAD

**Issue by bc88bc** [personlin/TGMM#9]
-999 is used to in some columns to represent NA (for example, column Rrup.NGA);
should replace -999 with NA

**Comment by personlin** [comment]
"Ztor.NGA"    "Strike.NGA"    "Dip.NGA"       "Rake.NGA"      "STA_Lat_Y.NGA" "STA_Lon_X.NGA" "EpiD.NGA"      "HypD.NGA"    "Rrup.NGA"      "Rjb.NGA"       "Rseis.NGA"     "RmsD.NGA"      "Rx.NGA"  
above columns were fixed.
